/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\yumaomoney\\my-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-2e483a1e",
    path: "/Examination/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e483a1e").then(next)
    },
  },
  {
    path: "/Examination/index.html",
    redirect: "/Examination/"
  },
  {
    name: "v-98a4dd54",
    path: "/FAQ/Console/A001.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-98a4dd54").then(next)
    },
  },
  {
    name: "v-918885d8",
    path: "/FAQ/Console/A002.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-918885d8").then(next)
    },
  },
  {
    name: "v-6ef0ed08",
    path: "/FAQ/DigestionHeap/DigestWill.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ef0ed08").then(next)
    },
  },
  {
    name: "v-66870da2",
    path: "/FAQ/DigestionHeap/Digested.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66870da2").then(next)
    },
  },
  {
    name: "v-dc8b2828",
    path: "/FAQ/DigestionHeap/Digesting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dc8b2828").then(next)
    },
  },
  {
    name: "v-4be95fe6",
    path: "/FAQ/Pool/Review.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4be95fe6").then(next)
    },
  },
  {
    name: "v-58c016d4",
    path: "/FAQ/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58c016d4").then(next)
    },
  },
  {
    path: "/FAQ/index.html",
    redirect: "/FAQ/"
  },
  {
    name: "v-2420a474",
    path: "/FAQ/Pool/SkillStack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2420a474").then(next)
    },
  },
  {
    name: "v-d14f4b96",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d14f4b96").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-b11f373e",
    path: "/Store/Anime/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b11f373e").then(next)
    },
  },
  {
    path: "/Store/Anime/index.html",
    redirect: "/Store/Anime/"
  },
  {
    name: "v-70ca92c0",
    path: "/Store/Apps/OwnTest.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70ca92c0").then(next)
    },
  },
  {
    name: "v-3fb7f5aa",
    path: "/Store/Apps/DownDoors.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3fb7f5aa").then(next)
    },
  },
  {
    name: "v-12d5236b",
    path: "/Store/Films/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12d5236b").then(next)
    },
  },
  {
    path: "/Store/Films/index.html",
    redirect: "/Store/Films/"
  },
  {
    name: "v-defb7404",
    path: "/Store/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-defb7404").then(next)
    },
  },
  {
    path: "/Store/index.html",
    redirect: "/Store/"
  },
  {
    name: "v-32c2884e",
    path: "/Thought/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32c2884e").then(next)
    },
  },
  {
    path: "/Thought/index.html",
    redirect: "/Thought/"
  },
  {
    name: "v-da5a6528",
    path: "/Thought/Travels/beiPing.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-da5a6528").then(next)
    },
  },
  {
    name: "v-5d499a06",
    path: "/Thought/YearReview/2018.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d499a06").then(next)
    },
  },
  {
    name: "v-4653a2b4",
    path: "/Thought/YearReview/2019.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4653a2b4").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]