/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "王志伟的博客",
  "description": "学习、生活、工作、总结",
  "base": "/Haymitch1992.github.io/",
  "pages": [
    {
      "title": "面试题",
      "frontmatter": {},
      "regularPath": "/Examination/",
      "relativePath": "Examination/README.md",
      "key": "v-2e483a1e",
      "path": "/Examination/",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/FAQ/DigestionHeap/DigestWill.html",
      "relativePath": "FAQ/DigestionHeap/DigestWill.md",
      "key": "v-6ef0ed08",
      "path": "/FAQ/DigestionHeap/DigestWill.html",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/FAQ/Console/A001.html",
      "relativePath": "FAQ/Console/A001.md",
      "key": "v-98a4dd54",
      "path": "/FAQ/Console/A001.html",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/FAQ/DigestionHeap/Digested.html",
      "relativePath": "FAQ/DigestionHeap/Digested.md",
      "key": "v-66870da2",
      "path": "/FAQ/DigestionHeap/Digested.html",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/FAQ/DigestionHeap/Digesting.html",
      "relativePath": "FAQ/DigestionHeap/Digesting.md",
      "key": "v-dc8b2828",
      "path": "/FAQ/DigestionHeap/Digesting.html",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/FAQ/Console/A002.html",
      "relativePath": "FAQ/Console/A002.md",
      "key": "v-918885d8",
      "path": "/FAQ/Console/A002.html",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/FAQ/Pool/Review.html",
      "relativePath": "FAQ/Pool/Review.md",
      "key": "v-4be95fe6",
      "path": "/FAQ/Pool/Review.html",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/FAQ/Pool/SkillStack.html",
      "relativePath": "FAQ/Pool/SkillStack.md",
      "key": "v-2420a474",
      "path": "/FAQ/Pool/SkillStack.html",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "title": "FAQ",
      "frontmatter": {},
      "regularPath": "/FAQ/",
      "relativePath": "FAQ/README.md",
      "key": "v-58c016d4",
      "path": "/FAQ/",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/Materials/",
      "relativePath": "Materials/README.md",
      "key": "v-7e280f28",
      "path": "/Materials/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/logo.jpg",
        "heroText": "Wiki 1001",
        "tagline": "Meet 1000 Books & Unit Them Into 1 Wiki",
        "actionText": "Get Wiki →",
        "actionLink": "/FAQ/",
        "features": [
          {
            "title": "Wiki - 求索",
            "details": "基于书签对知识点进行 整理，吸收，吐纳，归档。吾将上下而求索..."
          },
          {
            "title": "Store - 仓库",
            "details": "展望云仓库而归纳整理，方便行事&培养习惯。鱼和熊掌我全都要..."
          },
          {
            "title": "Thought - 随笔",
            "details": "活着，是一件最能带来满足感的事。细细琢磨吧，人生啊，有意思的很..."
          }
        ],
        "footer": "MIT Licensed | Copyright © 2019.01.11-present Mulander-J"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-d14f4b96",
      "path": "/",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "title": "首页",
      "frontmatter": {},
      "regularPath": "/Store/Anime/",
      "relativePath": "Store/Anime/README.md",
      "key": "v-b11f373e",
      "path": "/Store/Anime/",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/Store/Apps/DownDoors.html",
      "relativePath": "Store/Apps/DownDoors.md",
      "key": "v-3fb7f5aa",
      "path": "/Store/Apps/DownDoors.html",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/Store/Apps/OwnTest.html",
      "relativePath": "Store/Apps/OwnTest.md",
      "key": "v-70ca92c0",
      "path": "/Store/Apps/OwnTest.html",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/Store/Films/",
      "relativePath": "Store/Films/README.md",
      "key": "v-12d5236b",
      "path": "/Store/Films/",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "title": "首页",
      "frontmatter": {},
      "regularPath": "/Store/",
      "relativePath": "Store/README.md",
      "key": "v-defb7404",
      "path": "/Store/",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "title": "首页",
      "frontmatter": {},
      "regularPath": "/Thought/",
      "relativePath": "Thought/README.md",
      "key": "v-32c2884e",
      "path": "/Thought/",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/Thought/Travels/beiPing.html",
      "relativePath": "Thought/Travels/beiPing.md",
      "key": "v-da5a6528",
      "path": "/Thought/Travels/beiPing.html",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/Thought/YearReview/2018.html",
      "relativePath": "Thought/YearReview/2018.md",
      "key": "v-5d499a06",
      "path": "/Thought/YearReview/2018.html",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/Thought/YearReview/2019.html",
      "relativePath": "Thought/YearReview/2019.md",
      "key": "v-4653a2b4",
      "path": "/Thought/YearReview/2019.html",
      "lastUpdated": "7/17/2019, 10:19:12 AM"
    },
    {
      "title": "搭建博客",
      "frontmatter": {},
      "regularPath": "/Materials/Vuepress/Vuepress.html",
      "relativePath": "Materials/Vuepress/Vuepress.md",
      "key": "v-9c9acab4",
      "path": "/Materials/Vuepress/Vuepress.html",
      "headers": [
        {
          "level": 2,
          "title": "搭建博客",
          "slug": "搭建博客"
        },
        {
          "level": 3,
          "title": "1. 初始化项目",
          "slug": "_1-初始化项目"
        },
        {
          "level": 3,
          "title": "2. package.json 基本配置",
          "slug": "_2-package-json-基本配置"
        },
        {
          "level": 3,
          "title": "3. 基本目录结构",
          "slug": "_3-基本目录结构"
        },
        {
          "level": 3,
          "title": "4. 设置博客首页",
          "slug": "_4-设置博客首页"
        },
        {
          "level": 3,
          "title": "5. 部署在Github",
          "slug": "_5-部署在github"
        },
        {
          "level": 3,
          "title": "6. 发布到自己的个人域名下",
          "slug": "_6-发布到自己的个人域名下"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebarDepth": 4,
    "lastUpdated": "Last Updated",
    "nav": [
      {
        "text": "求索",
        "link": "/FAQ/"
      },
      {
        "text": "技术总结",
        "link": "/Materials/"
      },
      {
        "text": "仓库",
        "link": "/Store/"
      },
      {
        "text": "随笔",
        "link": "/Thought/"
      },
      {
        "text": "面试",
        "link": "/Examination/"
      },
      {
        "text": "Concat",
        "items": [
          {
            "text": "Segmentfault",
            "link": "https://segmentfault.com/u/mulander"
          }
        ]
      },
      {
        "text": "GitHub",
        "items": [
          {
            "text": "GitHub首页",
            "link": "https://github.com/Mulander-J"
          },
          {
            "text": "Island",
            "link": "https://mulander-j.github.io/island/code/html/index.html"
          },
          {
            "text": "TimeWaster",
            "link": "https://mulander-j.github.io/timeWaster/demo/index.html#/"
          }
        ]
      }
    ],
    "sidebar": {
      "/FAQ/": [
        {
          "title": "消化堆",
          "children": [
            [
              "/FAQ/DigestionHeap/Digested",
              "消化过"
            ],
            [
              "/FAQ/DigestionHeap/Digesting",
              "消化中"
            ],
            [
              "/FAQ/DigestionHeap/DigestWill",
              "待消化"
            ]
          ]
        },
        {
          "title": "输出层",
          "children": [
            [
              "/FAQ/Console/A001",
              "#A001_VuePress"
            ],
            [
              "/FAQ/Console/A002",
              "#A002_插件清单"
            ]
          ]
        },
        [
          "/FAQ/",
          "百科首页"
        ],
        [
          "/FAQ/Pool/SkillStack",
          "技术栈"
        ],
        [
          "/FAQ/Pool/Review",
          "归去来"
        ]
      ],
      "/Thought/": [
        [
          "/Thought/",
          "随笔首页"
        ],
        {
          "title": "游记",
          "children": [
            [
              "/Thought/Travels/beiPing",
              "北平游记"
            ]
          ]
        },
        {
          "title": "年终回顾",
          "children": [
            [
              "/Thought/YearReview/2018",
              "2018年"
            ],
            [
              "/Thought/YearReview/2019",
              "2019年"
            ]
          ]
        }
      ],
      "/Store/": [
        [
          "",
          "前端面试题"
        ],
        {
          "title": "应用",
          "children": [
            [
              "/Store/Apps/DownDoors",
              "下载门户"
            ],
            [
              "/Store/Apps/OwnTest",
              "博主测评"
            ]
          ]
        },
        {
          "title": "电影",
          "children": [
            [
              "/Store/Films/",
              "收藏级电影"
            ]
          ]
        },
        {
          "title": "动画",
          "children": [
            [
              "/Store/Anime/",
              "收藏级动画"
            ]
          ]
        }
      ],
      "/Examination/": [
        [
          "",
          "仓库首页"
        ]
      ],
      "/Materials/": [
        [
          "",
          "学习资料"
        ],
        {
          "title": "Vuepress",
          "children": [
            [
              "/Materials/Vuepress/Vuepress",
              "Vuepress搭建"
            ]
          ]
        }
      ]
    }
  }
}